version: "3"

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortenerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
