version: "3"

services:
  service:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: verystrongpassword
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: shortenerdb

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: verystrongpassword
      POSTGRES_DB: shortenerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://service:5000
    depends_on:
      - service

volumes:
  postgres_data:
